### PR TITLE
Add `autopep8`

### LINKED ISSUE #104: Add `autopep8` to the tools
I use `autopep8` as formatter (don't judge), and it gets pushed at the very end of my pyproject.toml. I expect it to be a bit higher. My guess is that I need to adjust the `fmt_tools()` method and place it somewhere close to `black`.

Speaking of it, how do the tools get their sorting order. They're not alphabetical, but categorical? If so, why is Ruff (linter) above isort (formatter)?

https://github.com/tox-dev/pyproject-fmt/blob/86892dff50a0969c300d7281cc105d39b5ee4256/src/pyproject_fmt/formatter/tools.py#L29-L41

### PR DESCRIPTION
**Pull request by kytta**
This PR adds `autopep8` to the list of tools.

Closes #104

### CODE REVIEW

**Review by gaborbernat — CHANGES_REQUESTED** [review]
Please add test.

**Comment by kytta** [comment]
Beat me to it :)

**Review by gaborbernat — APPROVED** [review]

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
